extends:
  - react-app
  - eslint:recommended
  - plugin:flowtype/recommended
  - plugin:jsx-a11y/recommended
  - plugin:react/recommended
  - plugin:sonarjs/recommended
  - plugin:prettier/recommended
rules:
  no-console: 1
  jsx-a11y/no-static-element-interactions: warn
  jsx-a11y/click-events-have-key-events: warn
  react/display-name: off
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
  sonarjs/cognitive-complexity: warn
  sonarjs/no-duplicate-string: warn
